version: "3.8"

x-common-pg: &common-pg
  build: hack/postgres
  ports:
    - "5432:5432"
  command: [ "postgres", "-c", "config_file=/pgc/postgresql.conf", "-c","hba_file=/pgc/pg_hba.conf" ]
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
  volumes:
    - ./hack/postgres:/pgc

services:
  pg_11:
    <<: *common-pg
    image: rueian/postgres:11-logical
  pg_12:
    <<: *common-pg
    image: dcard/postgres:12-logical
  pg_13:
    <<: *common-pg
    image: dcard/postgres:13-logical
  pulsar:
    image: apachepulsar/pulsar:2.10.4
    command: ["bin/pulsar", "standalone"]
    ports:
      - 6650:6650
      - 8080:8080
